version: '3'

networks:
  arnab:
    external: true

services:
  user-service-nginx-node:
    build:
      context: .
      dockerfile: Dockerfile.node.nginx
    container_name: user-service-nginx-node
    # ports:
    #   - "12301:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user-service-php
    networks:
      arnab:
        ipv4_address: 172.20.0.3

  user-service-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-php
    user: "setu:setu"
    volumes:
      - ./src:/usr/share/nginx/html
    # ports:
    #   - "9000:9000"
    working_dir: /usr/share/nginx/html
    networks:
      arnab:
        ipv4_address: 172.20.0.4
    environment:
      - USER_SERVICE_URL="http://localhost:8080/user-service"
      - POST_SERVICE_URL="http://localhost:8080/"
      - NOTIF_SERVICE_URL="http://localhost:8080/notif-service"

